name: Rust Docker Build Environment

on:
  push:
    branches:
      - master
  schedule:
    # Rebuild this every night at 5am pacific
    - cron: "0 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        id: publish
        if: github.ref == 'refs/heads/master'
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: khonsulabs/build-rust
          dockerfile: rust/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        env:
          DEBIAN_FRONTEND: noninteractive
